engine_config:
  model: Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8
  tensor_parallel_size: 4
extra_labels:
  openllm_alias: 72b-q8-3090-4
project: vllm-chat
service_config:
  name: qwen2.5
  resources:
    gpu: 4
    gpu_type: nvidia-rtx-3090
  traffic:
    timeout: 300
