"phi3:3.8b-mini-instruct-4k-fp16":
  alias:
    - latest
    - 3.8b
    - instruct
    - mini
  project: vllm-chat
  service_config:
    name: phi3
    traffic:
      timeout: 300
    resources:
      gpu: 1
      gpu_type: nvidia-tesla-t4
  engine_config:
    model: microsoft/Phi-3-mini-4k-instruct
    max_model_len: 4096
    dtype: half
  prompt:
    head: ~
    body: |-
      <|user|>
      {user_prompt}<|end|>
      <|assistant|>
"llama2:7b-chat-fp16":
  alias:
    - latest
    - 7b
    - 7b-chat
  project: vllm-chat
  service_config:
    name: llama2
    traffic:
      timeout: 300
    resources:
      gpu: 1
      gpu_type: nvidia-tesla-t4
  engine_config:
    model: meta-llama/Llama-2-7b-chat-hf
    max_model_len: 1024
  prompt:
    head: ~
    body: |-
      <s>[INST] <<SYS>>
      You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.
      If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
      <</SYS>>
      {user_prompt} [/INST] 
