engine_config:
  dtype: auto
  model: Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8
  tensor_parallel_size: 4
project: vllm-chat
service_config:
  name: qwen2.5
  resources:
    gpu: 4
    gpu_type: nvidia-a100-80g
  traffic:
    timeout: 300
