service: service:VLLM
name: llama3
version: 70b-instruct-fp16-3cbc
bentoml_version: 1.3.7
creation_time: '2024-09-27T09:46:41.061089+00:00'
labels:
  model_name: meta-llama/Meta-Llama-3-70B-Instruct
  openllm_alias: 70b,70b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
runners: []
entry_service: llama3
services:
- name: llama3
  service: ''
  models: []
  dependencies: []
  config:
    name: llama3
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80g
    traffic:
      timeout: 300
envs: []
schema:
  name: llama3
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
