project: vllm-chat
service_config:
  name: llama3.2
  traffic:
    timeout: 300
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
engine_config:
  model: meta-llama/Llama-3.2-11B-Vision-Instruct
  enforce_eager: true
  limit_mm_per_prompt:
    image: 1
  max_model_len: 16384
  max_num_seqs: 16
