alias:
  - 12b
project: vllm-chat
bentoml:
  service_args:
    name: llama3_2
    traffic:
      timeout: 300
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
vllm:
  engine_args:
    model: meta-llama/Llama-3.2-11B-Vision-Instruct
    enforce_eager: true
    limit_mm_per_prompt:
      image: 1
    max_model_len: 8192
    max_num_seqs: 16
